name: Deploy frontend on push/merge

on:
  push:
    branches:
      - main
    paths:
      - '*.json'
      - '*.js'
      - 'src/**'
      - '.github/workflows/prod-deploy-frontend.yml'

jobs:
  # Build the frontend giles
  build:
    name: Compile frontend

    runs-on: ubuntu-latest

    steps:

      # Environment and dependency setup
      - name: Cloning repository
        uses: actions/checkout@v1
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Set Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: npm i
      - name: Create environment files
        run: |
          echo -e "${{ secrets.DOTENV_PRODUCTION }}" > .env

      # Deployment
      - name: Build website files
        env:
          NODE_ENV: production
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,firestore --project=production
        env:
          GCP_SA_KEY: ${{ secrets.SERVICE_ACCOUNT_PRODUCTION }}
